"""add Column:count_boards in table:PCB

Revision ID: 05cd0e654573
Revises: 316757c956a5
Create Date: 2021-11-24 16:04:37.721085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cd0e654573'
down_revision = '316757c956a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PCB', sa.Column('count_boards', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PCB', 'count_boards')
    # ### end Alembic commands ###
