"""correct models

Revision ID: 6b0ec52f76ee
Revises: cd5267974173
Create Date: 2021-10-21 09:34:52.203959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0ec52f76ee'
down_revision = 'cd5267974173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('voltage', sa.String(length=10), nullable=True))
    op.add_column('components', sa.Column('power', sa.Float(), nullable=True))
    op.drop_column('components', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('unit', sa.VARCHAR(length=25), nullable=True))
    op.drop_column('components', 'power')
    op.drop_column('components', 'voltage')
    # ### end Alembic commands ###
