"""bug fix 'value in component is not unique'

Revision ID: 8d1041491dfa
Revises: 05cd0e654573
Create Date: 2021-11-26 12:05:29.351316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1041491dfa'
down_revision = '316757c956a5'  #'05cd0e654573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_components_value', table_name='components')
    op.create_index(op.f('ix_components_value'), 'components', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_components_value'), table_name='components')
    op.create_index('ix_components_value', 'components', ['value'], unique=False)
    # ### end Alembic commands ###
