"""empty message

Revision ID: c4d1fc0fcd79
Revises: 
Create Date: 2022-05-12 19:05:09.549730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d1fc0fcd79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PCB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Float(), nullable=True),
    sa.Column('count_boards', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('refdes', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_name'), 'patterns', ['name'], unique=True)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Integer(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category_name', sa.String(length=128), nullable=True),
    sa.Column('pattern_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['category_name'], ['categories.name'], ),
    sa.ForeignKeyConstraint(['pattern_name'], ['patterns.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_value'), 'components', ['value'], unique=False)
    op.create_table('component_pcb',
    sa.Column('pcb_id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('comp_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['pcb_id'], ['PCB.id'], ),
    sa.PrimaryKeyConstraint('pcb_id', 'comp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_pcb')
    op.drop_index(op.f('ix_components_value'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_patterns_name'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('PCB')
    # ### end Alembic commands ###
